version: '3.8'
services:
  # MySQL: 유저, 상품, 주문 저장
  db:
    image: mysql:8.4
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: krems_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # Redis: 인기 상품 캐싱
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

  # Elasticsearch: 상품 검색
  elasticsearch:
    image: elasticsearch:8.17.10
    container_name: es-search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false            # 아이디/비번 없이 접속 허용
      - xpack.security.http.ssl.enabled=false   # HTTPS가 아닌 HTTP 접속 허용
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"      # 메모리 설정
    ports:
      - "9200:9200"
