spring:
  application:
    name: krems
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              # - openid
              - profile  # 사용자 프로필 정보 접근, 예: 이름, 사진
              - email

jwt:
    secret: ${JWT_SECRET:default_jwt_secret_key}

management:
  endpoints:
    web:
      exposure:
        include: health
